### ISSUE TITLE
Add spellcheck and URI link validation on Markdown files in tests

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/DscResource.Tests#211]
To help improve the quality of the MD files in the DSC Resource Kit, we could add tests for spelling and URI link validation. As per discussion with @vors [here](https://github.com/PowerShell/platyPS/issues/345#issuecomment-371252054).

- Spellchecking: https://github.com/PowerShell/platyPS/issues/345#issuecomment-371252054
- Markdown link check: https://github.com/vors/MarkdownLinkCheck

These look like they could be added pretty easily. We'd want to use the "Opt-in" model for this like most tests.

**Comment by johlju** [comment]
All for this!

Not sure if it can be applied here, but this also have npm packages. For spell checking I use [Code Spell Checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker) in Visual Studio Code which uses [cspell](https://www.npmjs.com/package/cspell). Mostly because it has dictionaries for [several languages](https://www.npmjs.com/~jason-dent) ([source](https://github.com/Jason3S/cspell-dicts)), even Swedish 😍. It can test the code as well, like comment-based help and variables. Although I have a massive list of exclusions. 
The spell check with different dictionaries could be used when testing localization files. But that could be an enhancement down the line 😄

**Comment by johlju** [comment]
Looking at the MarkdownLinkCheck module, it seems it very outdated. The source Markdig is on version 0.15.1 now; https://github.com/lunet-io/markdig#download. Looking at the change log it feels that we want to use a newer version. 
Maybe we can use the module, but replace the .dll to a newer version before we import the module, or if we can download the npm and use it directly in some way?

**Comment by vors** [comment]
I bumped MarkdownLinkCheck to use 0.15.1 Markdig and published it as 0.2.0
Let me know if you see any problems!

**Comment by johlju** [comment]
@vors many thanks for updating the module for us! 😃

**Comment by johlju** [comment]
If cSpell is used for spelling, then the same configuration file can be used for the VSCode extension "Code Spell Checker". 
Personally I'm using this extension to spell check the code, and it helps making sure to not use abbreviations, and not making spelling mistakes in variables. Would be great if this could spell check at least comments in code, but that can be a future enhancement. First markdown I think. 🙂  

Also, the output of cSpell looked easier to parse, or rather, no need to parse it. 

No errors:
```
CSpell: Files checked: 1, Issues found: 0 in 0 files
```

Errors:
```
Tests/Integration/README.md:26:1 - Unknown word (DSCTABULAR)
Tests/Integration/README.md:74:57 - Unknown word (adatper)
Tests/Integration/README.md:96:1 - Unknown word (DSCRS)
Tests/Integration/README.md:181:31 - Unknown word (dbcreator)
Tests/Integration/README.md:188:1 - Unknown word (dbcreator)
CSpell: Files checked: 1, Issues found: 5 in 1 files
```

Install:

```
npm install -g cspell
cspell '**/*.md' -local 'en-US' --no-color  --config 'cSpell.json'
```
cSpell.json (stripped version of the config file used for SqlServerDsc):
```json
{
    "language": "en",
    "dictionaries": [
        "powershell"
    ],
    "words": [
        "Addnode",
        "AppVeyor",
        "CHANGELOG",
        "COMPUTERNAME",
        "DHCP"
    ],
    "ignorePaths": [
        ".git",
        "settings.json",
        "cSpell.json"
    ],
    "ignoreRegExpList": [
        "/windowsservercore/g",
        "/microsoft//windowsservercore/g",
        "/SQLAGENT\\$/g",
        "/SQLENGINE/g",
        "/\\.EXTERNALMODULEDEPENDENCIES/g",
        "sqlserverendpointstate",
    ]
}
```

**Comment by johlju** [comment]
@vors Tried MarkdownLinkCheck, and it finds broken links in my tests, but there are one issue, do you know if it can be solved (easily)? The issue is that it seems to think a correct link that points to a folder is broken. For example it fails on all the links in the README.md here.

https://github.com/PowerShell/SqlServerDsc/tree/dev/Examples

```
Path       : C:\Source\SqlServerDsc\Examples\README.md
Text       : SqlAG
Url        : /Examples/Resources/SqlAG
IsBroken   : True
IsAbsolute : False
Line       : 10
Column     : 3
```

**Comment by johlju** [comment]
Opened issue https://github.com/vors/MarkdownLinkCheck/issues/5 for previous comment.

**Comment by johlju** [comment]
Markdown link linting is proposed in PR #273. Looking at adding spell check when I have time.

**Comment by johlju** [comment]
Issue vors/MarkdownLinkCheck#5 is closed, I did not use relative path - made a review comment so we can add that to the docs.

**Comment by johlju** [comment]
Added PR #279 for spell-checking, although there is currently a problem with using cSpell, it sends output to stderr even when there is no error, submitted issue https://github.com/Jason3S/cspell/issues/61.
